version: '3.8'

services:
  app:
    build: .
    container_name: demomicroservices
    ports:
      - "8080:8080"
    environment:
      - TNS_ADMIN=/app/Wallet_YF7TJC6PMFWBDZF6
    volumes:
      - ./Wallet_YF7TJC6PMFWBDZF6:/app/Wallet_YF7TJC6PMFWBDZF6:ro
    restart: unless-stopped