CREATE USER EJEMPLO_SPRING IDENTIFIED BY "myContra.pract_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER EJEMPLO_SPRING QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO EJEMPLO_SPRING;
GRANT "RESOURCE" TO EJEMPLO_SPRING;
ALTER USER EJEMPLO_SPRING DEFAULT ROLE "RESOURCE";